use crate::domain::{Order, OrderId, OrderSide, TokenAmount};
use std::collections::{HashMap, HashSet, VecDeque};

/// Represents a match between two orders
#[derive(Debug, Clone)]
pub struct OrderMatch {
    /// First order in the match
    pub order_a: OrderId,
    /// Second order in the match
    pub order_b: OrderId,
    /// Matched volume (in sell token of order_a)
    pub volume: TokenAmount,
    /// Clearing price for the match
    pub price: f64,
    /// Surplus generated by this match
    pub surplus: f64,
}

/// Matching engine for finding CoW opportunities
pub struct MatchingEngine {
    /// Minimum price overlap required for matching (as percentage)
    min_price_overlap: f64,
    /// Enable partial fills
    allow_partial_fills: bool,
}

impl MatchingEngine {
    /// Create new matching engine with default settings
    pub fn new() -> Self {
        Self {
            min_price_overlap: 0.01, // 1% minimum overlap
            allow_partial_fills: true,
        }
    }

    /// Create matching engine with custom settings
    pub fn with_config(min_price_overlap: f64, allow_partial_fills: bool) -> Self {
        Self {
            min_price_overlap,
            allow_partial_fills,
        }
    }

    /// Find all CoW matches in a batch of orders
    /// Returns list of matches sorted by surplus (highest first)
    pub fn find_matches(&self, orders: &[Order]) -> Vec<OrderMatch> {
        let mut matches = Vec::new();

        // Build token pair index for efficient lookup
        let pair_index = self.build_pair_index(orders);

        // Find direct matches (A sells X for Y, B sells Y for X)
        for ((sell_token, buy_token), order_ids) in &pair_index {
            let reverse_pair = (buy_token.clone(), sell_token.clone());
            if let Some(reverse_order_ids) = pair_index.get(&reverse_pair) {
                // Found potential matches
                for &order_a_idx in order_ids {
                    for &order_b_idx in reverse_order_ids {
                        if let Some(order_match) =
                            self.try_match(&orders[order_a_idx], &orders[order_b_idx])
                        {
                            matches.push(order_match);
                        }
                    }
                }
            }
        }

        // Sort by surplus (highest first)
        matches.sort_by(|a, b| b.surplus.partial_cmp(&a.surplus).unwrap());

        // Remove overlapping matches (greedy selection)
        self.select_non_overlapping_matches(matches)
    }

    /// Find multi-hop CoW cycles (A→B→C→A)
    /// This enables more complex matching patterns
    pub fn find_cycles(&self, orders: &[Order]) -> Vec<Vec<OrderId>> {
        let mut cycles = Vec::new();

        // Build directed graph of potential trades
        let graph = self.build_trade_graph(orders);

        // Find cycles using DFS
        for order in orders {
            if let Some(cycle) = self.find_cycle_from(&order.id, &graph, orders) {
                if cycle.len() >= 3 {
                    // Only consider cycles of length 3+
                    cycles.push(cycle);
                }
            }
        }

        // Deduplicate cycles (same cycle can be found from different starting points)
        self.deduplicate_cycles(cycles)
    }

    /// Try to match two orders
    fn try_match(&self, order_a: &Order, order_b: &Order) -> Option<OrderMatch> {
        // Check if orders trade opposite tokens
        if order_a.sell_token != order_b.buy_token || order_a.buy_token != order_b.sell_token {
            return None;
        }

        // Calculate prices
        let price_a = order_a.buy_amount.0 as f64 / order_a.sell_amount.0 as f64;
        let price_b = order_b.buy_amount.0 as f64 / order_b.sell_amount.0 as f64;

        // Check price compatibility
        if !self.prices_overlap(price_a, price_b) {
            return None;
        }

        // Calculate clearing price (midpoint of overlap)
        let clearing_price = (price_a + price_b) / 2.0;

        // Calculate matched volume
        let volume = self.calculate_match_volume(order_a, order_b);

        // Calculate surplus
        let surplus = self.calculate_match_surplus(order_a, order_b, clearing_price, volume.0);

        Some(OrderMatch {
            order_a: order_a.id.clone(),
            order_b: order_b.id.clone(),
            volume,
            price: clearing_price,
            surplus,
        })
    }

    /// Check if two prices have sufficient overlap for matching
    fn prices_overlap(&self, price_a: f64, price_b: f64) -> bool {
        let overlap = (price_a - price_b).abs() / price_a.max(price_b);
        overlap <= self.min_price_overlap
    }

    /// Calculate the volume that can be matched between two orders
    fn calculate_match_volume(&self, order_a: &Order, order_b: &Order) -> TokenAmount {
        if self.allow_partial_fills {
            // Match minimum of available volumes
            let vol_a = order_a.sell_amount.0;
            let vol_b = order_b.buy_amount.0; // What order_b wants to buy
            TokenAmount(vol_a.min(vol_b))
        } else {
            // Full fill only - use smaller order
            TokenAmount(order_a.sell_amount.0.min(order_b.sell_amount.0))
        }
    }

    /// Calculate surplus generated by matching two orders
    fn calculate_match_surplus(
        &self,
        order_a: &Order,
        order_b: &Order,
        clearing_price: f64,
        volume: u128,
    ) -> f64 {
        // Surplus = difference between limit prices and clearing price
        let price_a = order_a.buy_amount.0 as f64 / order_a.sell_amount.0 as f64;
        let price_b = order_b.buy_amount.0 as f64 / order_b.sell_amount.0 as f64;

        let surplus_a = (clearing_price - price_a).abs() * volume as f64;
        let surplus_b = (clearing_price - price_b).abs() * volume as f64;

        surplus_a + surplus_b
    }

    /// Build index of orders by token pair
    fn build_pair_index(&self, orders: &[Order]) -> HashMap<(String, String), Vec<usize>> {
        let mut index: HashMap<(String, String), Vec<usize>> = HashMap::new();

        for (i, order) in orders.iter().enumerate() {
            let pair = (order.sell_token.clone(), order.buy_token.clone());
            index.entry(pair).or_default().push(i);
        }

        index
    }

    /// Select non-overlapping matches using greedy algorithm
    /// Ensures each order is only matched once
    fn select_non_overlapping_matches(&self, matches: Vec<OrderMatch>) -> Vec<OrderMatch> {
        let mut selected = Vec::new();
        let mut used_orders: HashSet<OrderId> = HashSet::new();

        for order_match in matches {
            // Check if either order is already used
            if !used_orders.contains(&order_match.order_a)
                && !used_orders.contains(&order_match.order_b)
            {
                used_orders.insert(order_match.order_a.clone());
                used_orders.insert(order_match.order_b.clone());
                selected.push(order_match);
            }
        }

        selected
    }

    /// Build directed graph of potential trades
    fn build_trade_graph(&self, orders: &[Order]) -> HashMap<OrderId, Vec<OrderId>> {
        let mut graph: HashMap<OrderId, Vec<OrderId>> = HashMap::new();

        for order_a in orders {
            for order_b in orders {
                if order_a.id != order_b.id && order_a.buy_token == order_b.sell_token {
                    // order_a can trade with order_b
                    graph
                        .entry(order_a.id.clone())
                        .or_default()
                        .push(order_b.id.clone());
                }
            }
        }

        graph
    }

    /// Find a cycle starting from a given order using DFS
    fn find_cycle_from(
        &self,
        start: &OrderId,
        graph: &HashMap<OrderId, Vec<OrderId>>,
        orders: &[Order],
    ) -> Option<Vec<OrderId>> {
        let mut visited = HashSet::new();
        let mut path = Vec::new();

        self.dfs_cycle(start, start, graph, &mut visited, &mut path)
    }

    /// DFS helper for cycle detection
    fn dfs_cycle(
        &self,
        current: &OrderId,
        start: &OrderId,
        graph: &HashMap<OrderId, Vec<OrderId>>,
        visited: &mut HashSet<OrderId>,
        path: &mut Vec<OrderId>,
    ) -> Option<Vec<OrderId>> {
        if path.len() > 0 && current == start {
            // Found cycle
            return Some(path.clone());
        }

        if visited.contains(current) || path.len() > 10 {
            // Avoid infinite loops and very long cycles
            return None;
        }

        visited.insert(current.clone());
        path.push(current.clone());

        if let Some(neighbors) = graph.get(current) {
            for neighbor in neighbors {
                if let Some(cycle) = self.dfs_cycle(neighbor, start, graph, visited, path) {
                    return Some(cycle);
                }
            }
        }

        path.pop();
        None
    }

    /// Remove duplicate cycles
    fn deduplicate_cycles(&self, cycles: Vec<Vec<OrderId>>) -> Vec<Vec<OrderId>> {
        let mut unique_cycles = Vec::new();
        let mut seen_sets: HashSet<HashSet<OrderId>> = HashSet::new();

        for cycle in cycles {
            let cycle_set: HashSet<OrderId> = cycle.iter().cloned().collect();
            if !seen_sets.contains(&cycle_set) {
                seen_sets.insert(cycle_set);
                unique_cycles.push(cycle);
            }
        }

        unique_cycles
    }
}

impl Default for MatchingEngine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::OrderSide;

    fn create_test_order(
        id: &str,
        sell_token: &str,
        buy_token: &str,
        sell_amount: u128,
        buy_amount: u128,
    ) -> Order {
        Order {
            id: OrderId(id.to_string()),
            sell_token: sell_token.to_string(),
            buy_token: buy_token.to_string(),
            sell_amount: TokenAmount(sell_amount),
            buy_amount: TokenAmount(buy_amount),
            side: OrderSide::Sell,
            valid_to: 0,
            partially_fillable: true,
        }
    }

    #[test]
    fn test_direct_match() {
        let engine = MatchingEngine::new();

        let orders = vec![
            create_test_order("1", "USDC", "DAI", 1000, 1000),
            create_test_order("2", "DAI", "USDC", 1000, 1000),
        ];

        let matches = engine.find_matches(&orders);
        assert_eq!(matches.len(), 1);
        assert!(matches[0].surplus >= 0.0);
    }

    #[test]
    fn test_no_match_different_tokens() {
        let engine = MatchingEngine::new();

        let orders = vec![
            create_test_order("1", "USDC", "DAI", 1000, 1000),
            create_test_order("2", "WETH", "USDC", 1, 2000),
        ];

        let matches = engine.find_matches(&orders);
        assert_eq!(matches.len(), 0);
    }

    #[test]
    fn test_price_overlap() {
        let engine = MatchingEngine::new();

        // Prices within 1% should match
        assert!(engine.prices_overlap(1.0, 1.005));
        assert!(engine.prices_overlap(1.0, 0.995));

        // Prices outside 1% should not match
        assert!(!engine.prices_overlap(1.0, 1.02));
        assert!(!engine.prices_overlap(1.0, 0.98));
    }

    #[test]
    fn test_volume_calculation() {
        let engine = MatchingEngine::new();

        let order_a = create_test_order("1", "USDC", "DAI", 1000, 1000);
        let order_b = create_test_order("2", "DAI", "USDC", 500, 500);

        let volume = engine.calculate_match_volume(&order_a, &order_b);
        assert_eq!(volume.0, 500); // Should match smaller volume
    }

    #[test]
    fn test_non_overlapping_selection() {
        let engine = MatchingEngine::new();

        let matches = vec![
            OrderMatch {
                order_a: OrderId("1".to_string()),
                order_b: OrderId("2".to_string()),
                volume: TokenAmount(100),
                price: 1.0,
                surplus: 10.0,
            },
            OrderMatch {
                order_a: OrderId("2".to_string()),
                order_b: OrderId("3".to_string()),
                volume: TokenAmount(100),
                price: 1.0,
                surplus: 8.0,
            },
            OrderMatch {
                order_a: OrderId("3".to_string()),
                order_b: OrderId("4".to_string()),
                volume: TokenAmount(100),
                price: 1.0,
                surplus: 6.0,
            },
        ];

        let selected = engine.select_non_overlapping_matches(matches);
        // Should select first and third match (non-overlapping)
        assert_eq!(selected.len(), 2);
        assert_eq!(selected[0].surplus, 10.0);
        assert_eq!(selected[1].surplus, 6.0);
    }

    #[test]
    fn test_cycle_detection() {
        let engine = MatchingEngine::new();

        // Create a cycle: A→B→C→A
        let orders = vec![
            create_test_order("A", "USDC", "DAI", 1000, 1000),
            create_test_order("B", "DAI", "WETH", 1000, 1),
            create_test_order("C", "WETH", "USDC", 1, 1000),
        ];

        let cycles = engine.find_cycles(&orders);
        assert!(!cycles.is_empty(), "Should find at least one cycle");
    }

    #[test]
    fn test_surplus_calculation() {
        let engine = MatchingEngine::new();

        let order_a = create_test_order("1", "USDC", "DAI", 1000, 1010);
        let order_b = create_test_order("2", "DAI", "USDC", 1000, 990);

        let clearing_price = 1.0;
        let volume = 1000;

        let surplus = engine.calculate_match_surplus(&order_a, &order_b, clearing_price, volume);
        assert!(surplus > 0.0, "Should generate positive surplus");
    }
}
